services:
  serverless:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "npx sls offline --host 0.0.0.0"
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    depends_on:
      - local-data-api
    environment:
      # needed in Rake tasks
      IS_OFFLINE: "true"
      TZ: Asia/Tokyo
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: mydatabase
  local-data-api:
    image: koxudaxi/local-data-api
    environment:
      ENGINE: PostgreSQLJDBC
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

